--[[
@module Deathknight Frost Rotation
GENERATED FROM SIMCRAFT PROFILE: Death_Knight_Frost_1h_T17N.simc
]]
local spells = kps.spells.deathknight
local env = kps.env.deathknight

kps.rotations.register("DEATHKNIGHT","FROST",
{
    {spells.deathsAdvance, 'player.isMoving'},
    {spells.antimagicShell},
    {spells.pillarOfFrost},
    {{"nested"}, 'activeEnemies() >= 3', {
        {spells.unholyBlight},
        {spells.defile},
        {spells.breathOfSindragosa, 'player.runicPower > 75'},
        {{"nested"}, 'target.hasMyDebuff(spells.breathOfSindragosa)', {
            {spells.howlingBlast},
            {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10'},
            {spells.deathAndDecay, 'player.unholyRunes = 1'},
            {spells.plagueStrike, 'player.unholyRunes = 2'},
            {spells.bloodTap},
            {spells.plagueLeech},
            {spells.plagueStrike, 'player.unholyRunes = 1'},
            {spells.empowerRuneWeapon},
        },
        {spells.howlingBlast},
        {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10'},
        {spells.frostStrike, 'player.runicPower > 88'},
        {spells.deathAndDecay, 'player.unholyRunes = 1'},
        {spells.plagueStrike, 'player.unholyRunes = 2'},
        {spells.bloodTap},
        {spells.frostStrike, 'not player.hasTalent(7, 3) or spells.breathOfSindragosa.cooldown >= 10'},
        {spells.plagueLeech},
        {spells.plagueStrike, 'player.unholyRunes = 1'},
        {spells.empowerRuneWeapon},
    },
    {{"nested"}, 'activeEnemies() < 3', {
        {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10 and ( player.runicPower > 76 or ( player.runicPower >= 20 and player.buffStacks(spells.killingMachine) ) )'},
        {spells.soulReaper, 'target.hp - 3 * ( target.hp % target.timeToDie ) <= 35'},
        {spells.bloodTap, '( target.hp - 3 * ( target.hp % target.timeToDie ) <= 35 and spells.soulReaper.cooldown = 0 )'},
        {spells.breathOfSindragosa, 'player.runicPower > 75'},
        {{"nested"}, 'target.hasMyDebuff(spells.breathOfSindragosa)', {
            {spells.obliterate, 'player.buffStacks(spells.killingMachine)'},
            {spells.bloodTap, 'player.buffStacks(spells.killingMachine) and player.buffStacks(spells.bloodCharge) >= 5'},
            {spells.plagueLeech, 'player.buffStacks(spells.killingMachine)'},
            {spells.howlingBlast, 'player.runicPower < 88'},
            {spells.obliterate, 'player.unholyRunes > 0 and player.runicPower < 76'},
            {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) >= 5'},
            {spells.plagueLeech},
            {spells.empowerRuneWeapon},
        },
        {spells.defile},
        {spells.bloodTap, 'player.hasTalent(7, 2) and spells.defile.cooldown = 0'},
        {spells.howlingBlast, 'player.hasTalent(7, 3) and spells.breathOfSindragosa.cooldown < 7 and player.runicPower < 88'},
        {spells.obliterate, 'player.hasTalent(7, 3) and spells.breathOfSindragosa.cooldown < 3 and player.runicPower < 76'},
        {spells.frostStrike, 'player.buffStacks(spells.killingMachine) or player.runicPower > 88'},
        {spells.frostStrike, 'spells.antimagicShell.cooldown < 1 and player.runicPower >= 50 and not player.hasBuff(spells.antimagicShell)'},
        {spells.howlingBlast, 'player.deathRunes > 1 or player.frostRunes > 1'},
        {spells.unholyBlight, 'not diseaseTicking()'},
        {spells.howlingBlast, 'not player.hasTalent(7, 1) and not target.hasMyDebuff(spells.frostFever)'},
        {spells.howlingBlast, 'player.hasTalent(7, 1) and not target.hasMyDebuff(spells.necroticPlague)'},
        {spells.plagueStrike, 'not player.hasTalent(7, 1) and not target.hasMyDebuff(spells.bloodPlague) and player.unholyRunes > 0'},
        {spells.howlingBlast, 'player.buffStacks(spells.rime)'},
        {spells.frostStrike, 'SimC Conversion ERROR'}, -- ERROR in 'set_bonus.tier17_2pc=1&(runic_power>=50&(cooldown.pillar_of_frost.remains<5))': Unkown expression 'set_bonus.tier17_2pc'!
        {spells.frostStrike, 'player.runicPower > 76'},
        {spells.obliterate, 'player.unholyRunes > 0 and not player.buffStacks(spells.killingMachine)'},
        {spells.howlingBlast, 'not ( target.hp - 3 * ( target.hp % target.timeToDie ) <= 35 and spells.soulReaper.cooldown < 3 ) or player.deathRunes + player.frostRunes >= 2'},
        {spells.bloodTap},
        {spells.plagueLeech},
        {spells.empowerRuneWeapon},
    },
}
,"Death_Knight_Frost_1h_T17N.simc")


kps.rotations.register("DEATHKNIGHT","FROST",
{
    {spells.deathsAdvance, 'player.isMoving'},
    {spells.antimagicShell},
    {spells.pillarOfFrost},
    {{"nested"}, 'activeEnemies() >= 4', {
        {spells.unholyBlight},
        {spells.defile},
        {spells.breathOfSindragosa, 'player.runicPower > 75'},
        {{"nested"}, 'target.hasMyDebuff(spells.breathOfSindragosa)', {
            {spells.howlingBlast},
            {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10'},
            {spells.deathAndDecay, 'player.unholyRunes = 1'},
            {spells.plagueStrike, 'player.unholyRunes = 2'},
            {spells.bloodTap},
            {spells.plagueLeech},
            {spells.plagueStrike, 'player.unholyRunes = 1'},
            {spells.empowerRuneWeapon},
        },
        {spells.howlingBlast},
        {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10'},
        {spells.frostStrike, 'player.runicPower > 88'},
        {spells.deathAndDecay, 'player.unholyRunes = 1'},
        {spells.plagueStrike, 'player.unholyRunes = 2'},
        {spells.bloodTap},
        {spells.frostStrike, 'not player.hasTalent(7, 3) or spells.breathOfSindragosa.cooldown >= 10'},
        {spells.plagueLeech},
        {spells.plagueStrike, 'player.unholyRunes = 1'},
        {spells.empowerRuneWeapon},
    },
    {{"nested"}, 'activeEnemies() < 4', {
        {spells.plagueLeech, 'diseaseMinRemains() < 1'},
        {spells.soulReaper, 'target.hp - 3 * ( target.hp % target.timeToDie ) <= 35'},
        {spells.bloodTap, '( target.hp - 3 * ( target.hp % target.timeToDie ) <= 35 and spells.soulReaper.cooldown = 0 )'},
        {spells.defile},
        {spells.bloodTap, 'player.hasTalent(7, 2) and spells.defile.cooldown = 0'},
        {spells.howlingBlast, 'player.buffStacks(spells.rime) and diseaseMinRemains() > 5 and player.buffStacks(spells.killingMachine)'},
        {spells.obliterate, 'player.buffStacks(spells.killingMachine)'},
        {spells.bloodTap, 'player.buffStacks(spells.killingMachine)'},
        {spells.howlingBlast, 'not player.hasTalent(7, 1) and not target.hasMyDebuff(spells.frostFever) and player.buffStacks(spells.rime)'},
        {spells.outbreak, 'not diseaseMaxTicking()'},
        {spells.unholyBlight, 'diseaseTicking()'},
        {spells.breathOfSindragosa, 'player.runicPower > 75'},
        {{"nested"}, 'target.hasMyDebuff(spells.breathOfSindragosa)', {
            {spells.obliterate, 'player.buffStacks(spells.killingMachine)'},
            {spells.bloodTap, 'player.buffStacks(spells.killingMachine) and player.buffStacks(spells.bloodCharge) >= 5'},
            {spells.plagueLeech, 'player.buffStacks(spells.killingMachine)'},
            {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) >= 5'},
            {spells.plagueLeech},
            {spells.obliterate, 'player.runicPower < 76'},
            {spells.howlingBlast, '( ( player.deathRunes = 1 and player.frostRunes = 0 and player.unholyRunes = 0 ) or player.deathRunes = 0 and player.frostRunes = 1 and player.unholyRunes = 0 ) and player.runicPower < 88'},
        },
        {spells.obliterate, 'player.hasTalent(7, 3) and spells.breathOfSindragosa.cooldown < 7 and player.runicPower < 76'},
        {spells.howlingBlast, 'player.hasTalent(7, 3) and spells.breathOfSindragosa.cooldown < 3 and player.runicPower < 88'},
        {spells.howlingBlast, 'not player.hasTalent(7, 1) and not target.hasMyDebuff(spells.frostFever)'},
        {spells.howlingBlast, 'player.hasTalent(7, 1) and not target.hasMyDebuff(spells.necroticPlague)'},
        {spells.plagueStrike, 'not player.hasTalent(7, 1) and not target.hasMyDebuff(spells.bloodPlague)'},
        {spells.bloodTap, 'player.buffStacks(spells.bloodCharge) > 10 and player.runicPower > 76'},
        {spells.frostStrike, 'player.runicPower > 76'},
        {spells.howlingBlast, 'player.buffStacks(spells.rime) and diseaseMinRemains() > 5 and ( player.bloodFraction >= 1.8 or player.unholyFraction >= 1.8 or player.frostFraction >= 1.8 )'},
        {spells.obliterate, 'player.bloodFraction >= 1.8 or player.unholyFraction >= 1.8 or player.frostFraction >= 1.8'},
        {spells.plagueLeech, 'diseaseMinRemains() < 3 and ( ( player.bloodFraction <= 0.95 and player.unholyFraction <= 0.95 ) or ( player.frostFraction <= 0.95 and player.unholyFraction <= 0.95 ) or ( player.frostFraction <= 0.95 and player.bloodFraction <= 0.95 ) )'},
        {spells.frostStrike, 'player.hasTalent(4, 2) and ( player.frostRunes = 0 or player.unholyRunes = 0 or player.bloodRunes = 0 ) and ( not player.buffStacks(spells.killingMachine) or not spells.obliterate.cooldown <= 1 )'},
        {spells.frostStrike, 'player.hasTalent(4, 1) and player.buffStacks(spells.bloodCharge) <= 10 and ( not player.buffStacks(spells.killingMachine) or not spells.obliterate.cooldown <= 1 )'},
        {spells.howlingBlast, 'player.buffStacks(spells.rime) and diseaseMinRemains() > 5'},
        {spells.obliterate, 'player.bloodFraction >= 1.5 or player.unholyFraction >= 1.6 or player.frostFraction >= 1.6 or player.bloodlust or spells.plagueLeech.cooldown <= 4'},
        {spells.bloodTap, '( player.buffStacks(spells.bloodCharge) > 10 and player.runicPower >= 20 ) or ( player.bloodFraction >= 1.4 or player.unholyFraction >= 1.6 or player.frostFraction >= 1.6 )'},
        {spells.frostStrike, 'not player.buffStacks(spells.killingMachine)'},
        {spells.plagueLeech, '( player.bloodFraction <= 0.95 and player.unholyFraction <= 0.95 ) or ( player.frostFraction <= 0.95 and player.unholyFraction <= 0.95 ) or ( player.frostFraction <= 0.95 and player.bloodFraction <= 0.95 )'},
        {spells.empowerRuneWeapon},
    },
}
,"Death_Knight_Frost_2h_T17N.simc")