--[[[
@module Warlock
@description
Warlock Spells and Environment Functions.
GENERATED FROM WOWHEAD SPELLS - DO NOT EDIT MANUALLY
]]--

kps.spells.warlock = {}

kps.spells.warlock.eyeOfKilrogg = kps.Spell.fromId(126)
kps.spells.warlock.corruption = kps.Spell.fromId(172)
kps.spells.warlock.immolate = kps.Spell.fromId(348)
kps.spells.warlock.shadowBolt = kps.Spell.fromId(686)
kps.spells.warlock.summonImp = kps.Spell.fromId(688)
kps.spells.warlock.drainLife = kps.Spell.fromId(689)
kps.spells.warlock.summonFelhunter = kps.Spell.fromId(691)
kps.spells.warlock.summonVoidwalker = kps.Spell.fromId(697)
kps.spells.warlock.ritualOfSummoning = kps.Spell.fromId(698)
kps.spells.warlock.banish = kps.Spell.fromId(710)
kps.spells.warlock.summonSuccubus = kps.Spell.fromId(712)
kps.spells.warlock.healthFunnel = kps.Spell.fromId(755)
kps.spells.warlock.agony = kps.Spell.fromId(980)
kps.spells.warlock.enslaveDemon = kps.Spell.fromId(1098)
kps.spells.warlock.summonInfernal = kps.Spell.fromId(1122)
kps.spells.warlock.lifeTap = kps.Spell.fromId(1454)
kps.spells.warlock.hellfire = kps.Spell.fromId(1949)
kps.spells.warlock.howlOfTerror = kps.Spell.fromId(5484)
kps.spells.warlock.unendingBreath = kps.Spell.fromId(5697)
kps.spells.warlock.rainOfFire = kps.Spell.fromId(5740)
kps.spells.warlock.fear = kps.Spell.fromId(5782)
kps.spells.warlock.felsteed = kps.Spell.fromId(5784)
kps.spells.warlock.createHealthstone = kps.Spell.fromId(6201)
kps.spells.warlock.soulFire = kps.Spell.fromId(6353)
kps.spells.warlock.mortalCoil = kps.Spell.fromId(6789)
kps.spells.warlock.shadowburn = kps.Spell.fromId(17877)
kps.spells.warlock.conflagrate = kps.Spell.fromId(17962)
kps.spells.warlock.summonDoomguard = kps.Spell.fromId(18540)
kps.spells.warlock.soulstone = kps.Spell.fromId(20707)
kps.spells.warlock.dreadsteed = kps.Spell.fromId(23161)
kps.spells.warlock.seedOfCorruption = kps.Spell.fromId(27243)
kps.spells.warlock.incinerate = kps.Spell.fromId(29722)
kps.spells.warlock.soulshatter = kps.Spell.fromId(29858)
kps.spells.warlock.createSoulwell = kps.Spell.fromId(29893)
kps.spells.warlock.unstableAffliction = kps.Spell.fromId(30108)
kps.spells.warlock.summonFelguard = kps.Spell.fromId(30146)
kps.spells.warlock.shadowfury = kps.Spell.fromId(30283)
kps.spells.warlock.demonicCircleSummon = kps.Spell.fromId(48018)
kps.spells.warlock.demonicCircleTeleport = kps.Spell.fromId(48020)
kps.spells.warlock.haunt = kps.Spell.fromId(48181)
kps.spells.warlock.glyphOfSubtlety = kps.Spell.fromId(56217)
kps.spells.warlock.glyphOfSiphonLife = kps.Spell.fromId(56218)
kps.spells.warlock.glyphOfHealthstone = kps.Spell.fromId(56224)
kps.spells.warlock.glyphOfSoulSwap = kps.Spell.fromId(56226)
kps.spells.warlock.glyphOfSoulstone = kps.Spell.fromId(56231)
kps.spells.warlock.glyphOfNightmares = kps.Spell.fromId(56232)
kps.spells.warlock.glyphOfUnstableAffliction = kps.Spell.fromId(56233)
kps.spells.warlock.glyphOfConflagrate = kps.Spell.fromId(56235)
kps.spells.warlock.glyphOfHealthFunnel = kps.Spell.fromId(56238)
kps.spells.warlock.glyphOfShadowBolt = kps.Spell.fromId(56240)
kps.spells.warlock.glyphOfVerdantSpheres = kps.Spell.fromId(56241)
kps.spells.warlock.glyphOfImpSwarm = kps.Spell.fromId(56242)
kps.spells.warlock.glyphOfFear = kps.Spell.fromId(56244)
kps.spells.warlock.glyphOfFelguard = kps.Spell.fromId(56246)
kps.spells.warlock.glyphOfFallingMeteor = kps.Spell.fromId(56247)
kps.spells.warlock.glyphOfHandOfGuldan = kps.Spell.fromId(56248)
kps.spells.warlock.glyphOfDemonTraining = kps.Spell.fromId(56249)
kps.spells.warlock.glyphOfSoulConsumption = kps.Spell.fromId(58070)
kps.spells.warlock.glyphOfUnendingBreath = kps.Spell.fromId(58079)
kps.spells.warlock.glyphOfEyeOfKilrogg = kps.Spell.fromId(58081)
kps.spells.warlock.glyphOfSoulwell = kps.Spell.fromId(58094)
kps.spells.warlock.glyphOfEnslaveDemon = kps.Spell.fromId(58107)
kps.spells.warlock.glyphOfDrainLife = kps.Spell.fromId(63302)
kps.spells.warlock.glyphOfEmberTap = kps.Spell.fromId(63304)
kps.spells.warlock.glyphOfDemonicCircle = kps.Spell.fromId(63309)
kps.spells.warlock.glyphOfCrimsonBanish = kps.Spell.fromId(63312)
kps.spells.warlock.glyphOfLifeTap = kps.Spell.fromId(63320)
kps.spells.warlock.soulburn = kps.Spell.fromId(74434)
kps.spells.warlock.masteryPotentAfflictions = kps.Spell.fromId(77215)
kps.spells.warlock.masteryMasterDemonologist = kps.Spell.fromId(77219)
kps.spells.warlock.masteryEmberstorm = kps.Spell.fromId(77220)
kps.spells.warlock.havoc = kps.Spell.fromId(80240)
kps.spells.warlock.soulSwap = kps.Spell.fromId(86121)
kps.spells.warlock.soulHarvest = kps.Spell.fromId(101976)
kps.spells.warlock.drainSoul = kps.Spell.fromId(103103)
kps.spells.warlock.metamorphosis = kps.Spell.fromId(103958)
kps.spells.warlock.demonicFury = kps.Spell.fromId(104315)
kps.spells.warlock.unendingResolve = kps.Spell.fromId(104773)
kps.spells.warlock.handOfGuldan = kps.Spell.fromId(105174)
kps.spells.warlock.darkRegeneration = kps.Spell.fromId(108359)
kps.spells.warlock.soulLeech = kps.Spell.fromId(108370)
kps.spells.warlock.harvestLife = kps.Spell.fromId(108371)
kps.spells.warlock.soulLink = kps.Spell.fromId(108415)
kps.spells.warlock.sacrificialPact = kps.Spell.fromId(108416)
kps.spells.warlock.unboundWill = kps.Spell.fromId(108482)
kps.spells.warlock.grimoireOfSupremacy = kps.Spell.fromId(108499)
kps.spells.warlock.grimoireOfService = kps.Spell.fromId(108501)
kps.spells.warlock.grimoireOfSacrifice = kps.Spell.fromId(108503)
kps.spells.warlock.archimondesDarkness = kps.Spell.fromId(108505)
kps.spells.warlock.mannorothsFury = kps.Spell.fromId(108508)
kps.spells.warlock.nightfall = kps.Spell.fromId(108558)
kps.spells.warlock.burningEmbers = kps.Spell.fromId(108647)
kps.spells.warlock.fireAndBrimstone = kps.Spell.fromId(108683)
kps.spells.warlock.decimation = kps.Spell.fromId(108869)
kps.spells.warlock.demonicLeap = kps.Spell.fromId(109151)
kps.spells.warlock.darkIntent = kps.Spell.fromId(109773)
kps.spells.warlock.aftermath = kps.Spell.fromId(109784)
kps.spells.warlock.darkBargain = kps.Spell.fromId(110913)
kps.spells.warlock.bloodHorror = kps.Spell.fromId(111397)
kps.spells.warlock.burningRush = kps.Spell.fromId(111400)
kps.spells.warlock.chaoticEnergy = kps.Spell.fromId(111546)
kps.spells.warlock.demonicGateway = kps.Spell.fromId(111771)
kps.spells.warlock.darkSoulInstability = kps.Spell.fromId(113858)
kps.spells.warlock.darkSoulMisery = kps.Spell.fromId(113860)
kps.spells.warlock.darkSoulKnowledge = kps.Spell.fromId(113861)
kps.spells.warlock.wildImps = kps.Spell.fromId(114592)
kps.spells.warlock.emberTap = kps.Spell.fromId(114635)
kps.spells.warlock.chaosBolt = kps.Spell.fromId(116858)
kps.spells.warlock.soulShards = kps.Spell.fromId(117198)
kps.spells.warlock.backdraft = kps.Spell.fromId(117896)
kps.spells.warlock.commandDemon = kps.Spell.fromId(119898)
kps.spells.warlock.flamesOfXoroth = kps.Spell.fromId(120451)
kps.spells.warlock.moltenCore = kps.Spell.fromId(122351)
kps.spells.warlock.doom = kps.Spell.fromId(124913)
kps.spells.warlock.glyphOfGatewayAttunement = kps.Spell.fromId(135557)
kps.spells.warlock.kiljaedensCunning = kps.Spell.fromId(137587)
kps.spells.warlock.glyphOfHavoc = kps.Spell.fromId(146962)
kps.spells.warlock.glyphOfUnendingResolve = kps.Spell.fromId(146964)
kps.spells.warlock.glyphOfEternalResolve = kps.Spell.fromId(148683)
kps.spells.warlock.demonicServitude = kps.Spell.fromId(152107)
kps.spells.warlock.cataclysm = kps.Spell.fromId(152108)
kps.spells.warlock.soulburnHaunt = kps.Spell.fromId(152109)
kps.spells.warlock.demonbolt = kps.Spell.fromId(157695)
kps.spells.warlock.charredRemains = kps.Spell.fromId(157696)
kps.spells.warlock.glyphOfDarkSoul = kps.Spell.fromId(159665)
kps.spells.warlock.glyphOfLifePact = kps.Spell.fromId(159669)
kps.spells.warlock.glyphOfMetamorphosis = kps.Spell.fromId(159680)
kps.spells.warlock.glyphOfShadowflame = kps.Spell.fromId(159688)
kps.spells.warlock.glyphOfTwilightWard = kps.Spell.fromId(159693)
kps.spells.warlock.glyphOfStrengthenedResolve = kps.Spell.fromId(159697)
kps.spells.warlock.devastation = kps.Spell.fromId(165363)
kps.spells.warlock.eradication = kps.Spell.fromId(165367)
kps.spells.warlock.demonicTactics = kps.Spell.fromId(165392)
kps.spells.warlock.bloodPact = kps.Spell.fromId(166928)
kps.spells.warlock.grimoireOfSynergy = kps.Spell.fromId(171975)
kps.spells.warlock.searingFlames = kps.Spell.fromId(174848)


kps.env.warlock = {}

function kps.env.warlock.isHavocUnit(unit)
    if not UnitExists(unit) then  return false end
    if UnitIsUnit("target",unit) then return false end
    return true
end
local burningRushLastMovement = 0
function kps.env.warlock.deactivateBurningRushIfNotMoving(seconds)
    return function ()
        if not seconds then seconds = 0 end
        local player = kps.env.player
        if player.isMoving or not player.hasBuff(kps.spells.warlock.burningRush) then
            burningRushLastMovement = GetTime()
        else
            local nonMovingDuration = GetTime() - burningRushLastMovement
            if nonMovingDuration >= seconds then
                RunMacroText("/cancelaura " .. kps.spells.warlock.burningRush)
            end
        end
    end
end

